/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kiyo' at '16/02/09 23:33' with Gradle 2.6
 *
 * @author kiyo, @date 16/02/09 23:33
 */
public class Library {
	public boolean someLibraryMethod() {
		return true;
	}
}
